version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./usr/src/app"
    depends_on:
      - db
      
  db:
    container_name: mySQL_db
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    
